// Content library.
//
// Two tiers:
//  • The FREE rotation (7 of each) — what free users cycle through, and what
//    the free CMS collections are seeded with.
//  • The PRO year library (365 of each) — served to Pro users by calendar date
//    (month/day assigned by position: item 1 → Jan 1 … item 365 → Dec 31).
//
// Stored as raw strings so ids and `order` are assigned by position in
// content_provider.dart. The 365s are organized into 12 themed months that walk
// the Functional Parenting framework. Voice: functional-behavior lens, warm,
// concise. Edit freely — or override any item in the in-app CMS after seeding.

// ── Free rotation (7 of each) ────────────────────────────────────────────────

const kFreeTipTexts = <String>[
  'Behavior is communication. Before you correct it, ask what it is trying to tell you.',
  'Connect before you direct — a regulated child hears you; a flooded one cannot.',
  'Name the feeling out loud. "You are really frustrated" lowers the temperature faster than "calm down."',
  'Give the transition a countdown. Surprise endings feel like losses to a child.',
  'Praise the effort, not the outcome. Effort is the thing they can repeat tomorrow.',
  'A consequence teaches best when it is small, immediate, and predictable — not big and delayed.',
  'Your calm is the intervention. Regulate yourself first, then the room follows.',
];

const kFreeChallengeSeeds = <(String, String)>[
  (
    'One-on-one ten',
    'Spend ten uninterrupted, phone-free minutes today letting your child lead the play.',
  ),
  (
    'Catch them being good',
    'Notice and name three positive behaviors out loud before dinner.',
  ),
  (
    'The pause',
    'Next time you feel the urge to react, take one slow breath before you respond.',
  ),
  ("Ask, don't tell", 'Replace one command today with a curious question.'),
  (
    'Name it to tame it',
    "Label your child's emotion once today before offering any solution.",
  ),
  (
    'Repair',
    'If a moment goes sideways, circle back later and reconnect. Repair is the lesson.',
  ),
  (
    'Predictable transition',
    'Give a five-minute warning before every transition today.',
  ),
];

const kFreeReflectionPrompts = <String>[
  'When did I feel most connected to my child today?',
  'What triggered me today, and what was underneath it?',
  "What was my child's behavior trying to communicate?",
  'Where did I respond instead of react? How did it go?',
  'What is one thing I want to do differently tomorrow?',
  'What did I handle well today that I want to remember?',
  'When did I model the calm I want my child to learn?',
];

// ─────────────────────────────────────────────────────────────────────────────
// TIPS — one line each (ParentingTip.text)
// ─────────────────────────────────────────────────────────────────────────────

const kTipTexts = <String>[
  // ── Month 1 · Foundations ──────────────────────────────────────────────────
  'Behavior is a message, not a malfunction. Ask "what is this need?" before "how do I stop it?"',
  'Every behavior is trying to get something or get away from something. Find the function and you find the fix.',
  "You don't have to fix the feeling to be a good parent — you have to stay while it passes.",
  'Misbehavior usually means a skill is missing, not that your child is being bad.',
  "The goal isn't a compliant child; it's a capable one. Compliance fades, skills last.",
  "Connection isn't a reward for good behavior — it's the soil good behavior grows in.",
  'Your calm is contagious, and so is your chaos. You set the emotional thermostat.',
  "When you don't know what to do, do less and stay close. Presence buys you time.",
  'A child who feels understood has far less to fight about.',
  'Punishment pauses behavior for a moment; teaching changes it for good.',
  "Catch the behavior you want more often than the behavior you don't. Attention is fertilizer.",
  'Big reactions teach kids that big behavior earns big attention. Keep your response small and steady.',
  'Kids do well when they can. Competence comes before cooperation.',
  'Name what you see without judging it: "You\'re having a hard time getting started." Understanding lowers the walls.',
  'Consistency is kinder than intensity. A calm limit held every time beats a loud one held sometimes.',
  "Before you correct, connect. A flooded brain can't learn.",
  'The behavior on the surface is rarely the real problem. Look underneath for tired, hungry, scared, or overwhelmed.',
  'You can set a limit and hold the feeling at the same time. Both can be true.',
  'Rules without relationship breed resistance. Invest in the bond first.',
  'Progress looks like the same struggle handled a little better — not the struggle disappearing.',
  'Describe, don\'t label. "The toys are still out" invites action; "You\'re so messy" invites shame.',
  "Your child's meltdown isn't a grade on your parenting — your response to it is the parenting.",
  "When you slow down, your child's nervous system borrows your steadiness.",
  'A predictable parent feels safe, and safety is what lets a child cooperate.',
  "You can't teach a lesson in the middle of a storm. Wait for calm, then teach.",
  "Every hard behavior is also information about what your child can't yet handle alone.",
  'The relationship is the strategy. Everything else is a technique that only works on top of it.',
  'Lower the demand before you raise your voice. Often the task, not the child, is the problem.',
  'Kids repeat what gets a reaction. Decide which behaviors deserve your energy.',
  "You don't need the perfect words. A warm tone and a steady presence do most of the work.",
  'Start where your child is, not where you wish they were. Meet reality first.',

  // ── Month 2 · Reset the Parent ─────────────────────────────────────────────
  "You are your child's first regulation tool. You can't pour calm from an empty cup.",
  'Name your own feeling before you manage theirs: "I\'m getting frustrated." Awareness is the brake.',
  'The pause between trigger and reaction is where your best parenting lives. Widen it.',
  'Your child inherits your nervous system before they inherit your words.',
  'When you feel the heat rise, drop your shoulders and slow your exhale. The body leads the mind down.',
  "You don't have to win the moment. You have to stay the adult in it.",
  'Guilt says "I made a mistake." Shame says "I am a mistake." Only one helps you grow.',
  "The parent you are when you're depleted isn't the real you — it's the tired you. Refuel without apology.",
  'Notice your triggers on the calm days, so you recognize them on the hard ones.',
  'Responding takes a beat; reacting takes none. Buy yourself the beat.',
  'You can apologize for your tone without undoing the limit. Repair and boundaries coexist.',
  "Your kids don't need a perfect parent. They need one who keeps coming back.",
  'When everything in you wants to yell, whisper instead. It resets you both.',
  "Self-compassion isn't soft — it's what keeps you from passing your stress down the line.",
  'The story you tell yourself about the behavior sets your reaction. Choose a kinder story.',
  'HALT before you react: are you Hungry, Angry, Lonely, or Tired? Often the need to feed is yours.',
  "Step away for thirty seconds instead of saying the thing you'll regret. Leaving is allowed.",
  "Your child's behavior can borrow your calm or your chaos. You decide which you lend.",
  'What you model in conflict teaches more than what you say in calm.',
  'A short fuse is usually a full plate. Lighten the load before you blame the child.',
  'You are allowed to have needs. Meeting them makes you a better parent, not a worse one.',
  "The goal isn't to never lose it. It's to notice sooner and repair faster.",
  "Breathe out longer than you breathe in. Your body can't panic and exhale slowly at once.",
  "Your worst parenting moments don't define you. Your repair does.",
  'Lower your expectations of a hard day, not your love. Grace scales.',
  "When you're triggered, your child feels as big and out of control as you do. Get small and steady.",
  'Ask "what do I need right now?" as often as you ask it of your kids.',
  "Rest isn't a reward for finishing. It's the fuel that lets you keep going.",
  "You can't teach regulation you don't practice. Your calm is the curriculum.",
  "Forgive yourself for yesterday's blowup so you're not parenting from guilt today.",
  'The most powerful thing you can do in a storm is nothing — just breathe and stay.',

  // ── Month 3 · Connection ───────────────────────────────────────────────────
  'Ten minutes of full attention prevents an hour of attention-seeking.',
  "Connection isn't earned by good behavior; it's the reason good behavior shows up.",
  "Follow your child's lead in play today. Being chosen tells them they matter.",
  'The child who acts least lovable often needs love the most.',
  'Greet your child at every reunion like the best part of your day just walked in.',
  'Fill the tank before you make the ask. A connected child cooperates more easily.',
  'Put the phone down when they talk. Divided attention feels like no attention to a child.',
  "A hand on the shoulder can say what a hundred words can't.",
  'Delight in your child out loud today. Being enjoyed builds worth.',
  "Special time works because it's predictable and unconditional — not a prize to lose.",
  'Get on their level, literally. Eye to eye lowers the walls.',
  'Learn a little about what your child loves. Interest is love in action.',
  'Connection repairs faster than any consequence. Reach for it first after a hard moment.',
  'Kids spell love T-I-M-E. Small, frequent moments beat rare grand gestures.',
  'When behavior spikes, ask: has the connection tank run low lately?',
  'Laugh with your child today. Play is the shortest bridge back to each other.',
  "Say your child's name warmly before you ask anything of them. It opens the door.",
  'A five-minute snuggle can regulate a whole afternoon.',
  "Be curious about your child's world instead of only managing their behavior.",
  'Attention gets spent somewhere. Invest it in what you want more of.',
  'The relationship is the account; every warm moment is a deposit against the hard ones.',
  'Let your child overhear you saying something kind about them.',
  'Presence beats presents. What they remember is that you were there.',
  "When you don't know how to help, sit close and stay. Connection is the help.",
  'Repair a disconnection today, even a small one. The reaching matters more than the words.',
  "Your warmth isn't a reward you ration. It's the ground they stand on.",
  'Ask one question today just to know them better, not to check on them.',
  'A child who feels seen has far less to prove.',
  'Slow down enough to actually notice your child today. Being noticed is being loved.',
  'The strongest limits sit on the strongest bonds. Build the bond first.',
  "End the day with connection, not correction. It's the note they fall asleep on.",

  // ── Month 4 · Define the Goal ──────────────────────────────────────────────
  'Ask not "how do I stop this?" but "what do I want them to do instead?" Aim at the skill.',
  'Behind every behavior you want to end is a skill you want to build. Teach the skill.',
  'Compliance is borrowed; competence is owned. Build the thing they keep.',
  'Name the positive opposite: not "stop whining" but "ask in your strong voice."',
  "You're not raising an obedient child, you're raising a capable adult. Parent for the long game.",
  'A goal you can picture is a goal you can teach. Get specific about the behavior you want.',
  'Kids can\'t do a "don\'t." Give them a "do" they can actually practice.',
  "Every misbehavior is a skill under construction. Coach it, don't just correct it.",
  "Decide what you're building this week, then catch every brick of it.",
  'The behavior is the symptom; the missing skill is the target. Aim there.',
  'Turn "be good" into something teachable: wait, ask, share, try again.',
  'Progress is a skill done a little more often, not a behavior gone forever.',
  'If you only stop the behavior, it returns. If you teach the replacement, it fades.',
  'Picture your child at 25. Which skill you teach today still matters then?',
  'Frustration tolerance, flexibility, asking for help — these are taught, not born. Start small.',
  'Choose one skill to grow this month and let the small stuff go.',
  'A clear goal turns discipline from punishment into teaching.',
  'Ask "what\'s hard for my child here?" — the answer is your lesson plan.',
  'Skills grow at the edge of easy. Set the bar just above where they are now.',
  'Reward the attempt at the new skill, not just the success. Effort is the seed.',
  "You can't expect a skill you've never taught. Model it before you require it.",
  "Replace the behavior, don't just remove it. Nature fills a vacuum.",
  'Name the skill out loud when they use it: "You waited your turn — that\'s patience."',
  "The tantrum is telling you which skill isn't online yet. Teach it when calm.",
  'Big goals, tiny steps. Master one rung before adding the next.',
  'What you practice grows. Give the good skill more reps than the bad habit gets reactions.',
  'Teaching a skill takes ten calm repetitions, not one loud correction.',
  'Define success small enough that your child can actually reach it today.',
  "The point isn't a quiet house; it's a child who can handle a loud feeling.",
  'Turn every recurring battle into a skill-building project. Same fight, new frame.',
  "Aim for progress you can name, and you'll both know when it's working.",

  // ── Month 5 · Decode the Function ──────────────────────────────────────────
  'Every behavior serves a purpose: attention, escape, a tangible, or a body that needs regulating.',
  'Ask "what happened right before, and what did the behavior get?" That\'s the function.',
  'Same behavior, different reasons. Two kids yelling may need opposite responses.',
  'If the behavior gets attention and keeps happening, attention is the fuel. Change what earns it.',
  'Behavior that ends a demand is escape. The task, not the child, is usually the problem.',
  "When the meltdown gets the toy, you've taught the toy is worth a meltdown.",
  "A dysregulated child isn't seeking anything — their body is overwhelmed. Calm first, teach later.",
  "Function beats form. Solve why it's happening, not just what it looks like.",
  'Track a behavior for a few days and the pattern — the function — reveals itself.',
  'Attention-seeking is connection-seeking in disguise. Give the connection freely.',
  "If your child acts up when you're on the phone, that's data, not defiance.",
  'Escape behavior spikes with hard tasks. Shrink the task and the behavior shrinks.',
  'Give the item after a tantrum and you strengthen the tantrum, not the child.',
  'Sensory-seeking bodies need movement, not a lecture. Read the need under the behavior.',
  'The four functions are your diagnostic. Name the function, then you know the fix.',
  'A behavior that "comes out of nowhere" always came from somewhere. Look upstream.',
  "When you can't find the function, ask: what does this behavior reliably produce?",
  "Kids don't misbehave to ruin your day. They behave to meet a need they can't name.",
  'If ignoring makes it worse before better, attention was the function — hold steady.',
  'Escape isn\'t laziness. It\'s "this is too hard for me right now." Meet that honestly.',
  'The same tantrum at bedtime and at the store may have two different engines.',
  "Reinforcement is anything that makes a behavior happen more. Find what's reinforcing this one.",
  'Change the antecedent and you often prevent the behavior — no consequence required.',
  'Ask what your child is "getting" from the behavior, then offer a better way to get it.',
  "A behavior's function tells you what to teach instead. It's a map, not a verdict.",
  'When the behavior works, it repeats. Make the appropriate way work better.',
  'Regulation-driven behavior needs a calmer environment, not a firmer consequence.',
  'Notice what you do right after the behavior — you may be its accidental reward.',
  'Two questions decode most behavior: what set it off, and what did it achieve?',
  'The function is the "why." Skip it, and every strategy is a guess.',
  'Once you see the function, you stop taking the behavior personally.',

  // ── Month 6 · Structure & Routines ─────────────────────────────────────────
  "Structure isn't the opposite of warmth — it's a form of it. Predictability feels like safety.",
  "A child who knows what's next has less to resist. Make the day visible.",
  "Routines carry the load so your willpower doesn't have to. Build the rails.",
  'Most "behavior problems" at transitions are really warning problems. Give the heads-up.',
  'Decide the rule once, calmly, before the moment — not in the heat of it.',
  'The environment shapes behavior. Change the setup before you correct the child.',
  'Put the tempting thing out of sight and you prevent half the battles.',
  "Consistency turns a rule into a rhythm. Rhythms don't need enforcing.",
  'A visual schedule ends a dozen daily negotiations. Let the chart be the boss.',
  'Transitions are hard because they feel like losses. Warn, acknowledge, then move.',
  'Same bedtime, same steps, every night. Boring is the goal — boring is calming.',
  'Front-load the hard parts of the day with structure, not with reminders.',
  'When mornings melt down, fix the system the night before.',
  'Kids test loudest where the limits move. Hold the line and the testing quiets.',
  'Build the routine when things are calm; lean on it when things are not.',
  "A timer is a neutral third party. Let it end the screen time so you don't have to.",
  'First-then is the smallest, strongest structure: "First shoes, then park."',
  'Predictable consequences teach; surprise ones just scare. Say it before you need it.',
  'Reduce the choices at hard moments. Two options beat an open field.',
  'Preview what\'s coming: "At Grandma\'s, we use gentle hands." Preview prevents.',
  'The calm before the transition is where you win the transition.',
  "Structure the environment for success and you'll correct less all day.",
  'A consistent no today prevents ten hopeful asks tomorrow.',
  'Anchor the day with a few fixed points; let the rest flex.',
  'When behavior worsens, check the basics first: sleep, food, downtime, predictability.',
  'Make the good choice the easy choice. Design the path you want them to take.',
  'Routines are promises. Keep them and your word becomes something they can lean on.',
  'A five-minute warning is the cheapest tantrum insurance you can buy.',
  'Chaos invites big behavior; order invites calm. Tidy the moment before you tidy the child.',
  "Let the schedule hold the limit so the relationship doesn't have to.",
  'Small, boring consistency beats big, occasional effort every single time.',

  // ── Month 7 · Limits & Follow-through ──────────────────────────────────────
  'A limit held with warmth is a gift, not a punishment. Kids feel safest inside clear edges.',
  'Say it once, then act. Repeating teaches your words are optional.',
  'Empathy plus a boundary: "I know you\'re upset, and we\'re still leaving." Both, not either.',
  'The limit stays whether they like it or not. Feelings can be big; the line stays put.',
  "Don't argue the boundary. State it, hold it, and let the feelings come.",
  'Follow-through is love in action. It tells your child the world is reliable.',
  'A calm "no" you keep beats an angry "no" you cave on.',
  'Give the limit, then get quiet. Over-explaining invites negotiation.',
  "Consequences work best when they're small, related, and certain — not big and dramatic.",
  'Offer choices inside the boundary, not about it: "Walk or be carried — you pick."',
  "If you're not willing to enforce it, don't say it. Only make limits you'll keep.",
  "Meltdowns after a limit aren't proof you're wrong. They're proof the limit mattered.",
  'Hold the boundary and hold your child. Firmness and tenderness are teammates.',
  'Your calm certainty is more convincing than any threat.',
  'The tantrum is the bill for the boundary. Pay it calmly; the limit still stands.',
  "Threats you won't keep spend your credibility. Promise only what you'll do.",
  'A boundary is information, not rejection. Deliver it like a fact, not a fight.',
  'When you cave to stop the crying, you teach that crying is the price of a yes.',
  "Decide your bottom line before the moment, so you're not negotiating with a flooded child.",
  '"I won\'t let you" is a full sentence. You can stop a behavior without a lecture.',
  'Kids feel your wobble. Stand steady and the storm passes faster.',
  'Natural consequences teach without a villain. Let the world do some of the teaching.',
  'Say what you\'ll do, not what they must do: "I\'ll read once you\'re in bed."',
  'A limit you hold today is ten arguments you skip tomorrow.',
  "You can be your child's safe place and their firm boundary at the same time.",
  'Warn once, follow through once. Predictable beats loud.',
  "The point of a limit isn't to win. It's to keep everyone safe and teach what holds.",
  "When you mean it, you don't have to raise your voice. Certainty is quiet.",
  'Boundaries without empathy feel harsh; empathy without boundaries feels unsafe. Give both.',
  'Let the consequence do the teaching, and keep your relationship out of the crossfire.',
  'Hold the line kindly enough times and the line stops needing defending.',

  // ── Month 8 · Big Feelings ─────────────────────────────────────────────────
  'All feelings are allowed; all behaviors are not. Welcome the emotion, guide the action.',
  'Name it to tame it: putting words to a feeling turns down its volume.',
  "A child in a big feeling can't reach logic. Comfort first; reason later.",
  'Your calm presence is the co-regulation. You are the anchor, not the fixer.',
  '"You\'re safe. I\'m here." does more than any explanation mid-meltdown.',
  "Don't rush the feeling out the door. Feelings that are felt fully pass faster.",
  "Behind anger is almost always hurt, fear, or overwhelm. Answer what's underneath.",
  'Validate before you solve: "That\'s so disappointing" opens ears advice would close.',
  "Meltdowns aren't manipulation — they're a nervous system past its limit. Meet them with calm.",
  'Let your child borrow your steadiness until their own comes back online.',
  'You don\'t have to agree with the feeling to honor it. "You really wanted that" costs nothing.',
  'Sit beside the storm instead of trying to stop it. Presence is the intervention.',
  '"Calm down" rarely calms anyone. "I\'m right here with you" does.',
  'Big feelings in small people need a big, steady adult — not a bigger reaction.',
  'Teach that a feeling has a name, a size, and an end. All feelings pass.',
  'Comfort the child, then address the behavior — never at the same time.',
  "Your child's meltdown isn't an emergency to fix. It's a wave to weather together.",
  'Emotion coaching: notice, name, allow, then guide. Skip a step and it stalls.',
  'When you stay calm through their storm, you teach their brain that storms are survivable.',
  'Don\'t take the "I hate you" personally. It\'s the size of the feeling, not the truth of it.',
  'Lower your voice when theirs goes up. You lead the tone down.',
  'Let them fall apart safely now so they can hold it together later.',
  'A regulated adult is worth more than the perfect words. Be the calm.',
  'Feelings need a witness, not a lecture. Sometimes "I see you" is the whole job.',
  'After the storm, reconnect before you correct. The lesson lands on calm ground.',
  'Give the feeling somewhere to go: a stomp, a squeeze, a breath, a hug.',
  "Your job isn't to make the sadness stop. It's to make sure they're not alone in it.",
  'Model your own feelings in small doses: "I felt frustrated, so I took a breath."',
  "Empathy doesn't spoil a child. Being alone in big feelings does the harm.",
  'The nervous system calms in the presence of a calmer one. Be that presence.',
  'Teach that brave and scared can live together, and so can love and anger.',

  // ── Month 9 · Respond with Purpose ─────────────────────────────────────────
  'What you pay attention to grows. Aim your attention at the behavior you want to see again.',
  'Praise the specific action, not the child: "You shared" teaches; "good boy" doesn\'t.',
  'Catch them being good and say it out loud. Noticed behavior repeats.',
  'Reinforce the replacement the moment it appears, before the old habit takes back over.',
  'A quick, warm "yes, like that" teaches faster than a long "no, not that."',
  'Reward effort and strategy, not just results. Those are what they can repeat.',
  'Your attention is the most powerful reinforcer you own. Spend it on purpose.',
  'Respond to the appropriate ask faster than you respond to the loud one.',
  'When the good behavior gets more payoff than the bad, the good behavior wins.',
  'Descriptive praise is a mirror: "You kept trying even when it was hard" shows them who they are.',
  'Notice the small step in the right direction. Progress starved of attention stalls.',
  "Make the calm request work every time and the meltdown work never. That's the whole game.",
  'Praise privately and specifically; it lands deeper than a public label.',
  'Reinforce quickly. A reward an hour later barely connects to the moment.',
  "Teach the do, reinforce the do, and the don't fades on its own.",
  'A high-five for the hard-won behavior beats a sticker for the easy one.',
  'Your delight is the reward kids chase hardest. Let it show when they get it right.',
  'When you must correct, keep it brief; when you can praise, make it specific.',
  'Grow the behavior you want with your best attention, not your leftover attention.',
  '"Thank you for using gentle hands" reinforces the exact thing you want more of.',
  "Reinforcement isn't bribery. Bribery comes before to stop a fit; reinforcement comes after to teach.",
  'Shine your spotlight on the try, and the try becomes the habit.',
  'The behavior that gets noticed gets repeated. Choose what you notice.',
  'Reconnect after cooperation, too — not just after conflict. Reward the peace.',
  'Small, immediate, sincere praise beats big, delayed, generic praise.',
  'Name the skill as you praise it, so they learn what to call their own success.',
  'Respond to progress, not perfection, and progress keeps coming.',
  'Every time the good behavior works, you make the bad behavior less necessary.',
  'Be as quick to notice the recovery as you were to notice the meltdown.',
  'Attention withheld from small good moments gets spent on big bad ones. Flip it.',
  'Teach on purpose, reinforce on purpose, and let the rest go.',

  // ── Month 10 · Everyday Battles ────────────────────────────────────────────
  'Mornings go smoother when the decisions are made the night before.',
  'Hunger and tiredness fake most "bad behavior." Feed and rest before you correct.',
  'At the store, say the plan out loud before you walk in. Preview beats damage control.',
  'Screen-time fights shrink when the timer, not you, calls the end.',
  'Sibling conflict: name the shared goal, not the villain. "You both want a turn."',
  "Don't referee every squabble. Coach the skills, then let them practice.",
  'Bedtime stalling is often a bid for connection. Front-load the snuggle to end the loop.',
  'Homework battles ease when you shrink the task: "Just the first problem."',
  'Pick your two non-negotiables and hold those; flex on the rest.',
  'The restaurant meltdown starts before the restaurant. Set expectations in the car.',
  "Whining is a skill gap, not a character flaw. Teach the words you'd rather hear.",
  'Getting-out-the-door chaos calms with a visual checklist they can own.',
  'When siblings compete for attention, give it freely at calm times so they stop fighting for it.',
  'Let natural hunger, not a battle, end the "I won\'t eat that" standoff.',
  'Transitions off fun things need a warning and a next thing to move toward.',
  'The car-seat fight ends faster with a calm, boring, every-time routine.',
  "Don't negotiate with a tired child at bedtime. Decide it earlier, hold it kindly.",
  'Turn chores into a first-then, not a lecture: "First tidy, then show me."',
  'Public behavior is private practice on display. Teach it at home first.',
  'Most mealtime power struggles ease when you offer the food and drop the pressure.',
  'Give the dawdler a countdown and a job, not a nag.',
  "Screen transitions land softer when you name what's next, not just what's ending.",
  'Two kids, one toy: coach the negotiation instead of confiscating the toy.',
  'The morning rush is a systems problem. Fix the system, not the child.',
  'Keep a snack and a plan in your bag. Half of public meltdowns are prevented, not managed.',
  "Bedtime works when it's the same, calm, and unhurried. Slow is fast here.",
  'When homework becomes a fight, protect the relationship and shrink the demand.',
  'Let siblings solve the small stuff. Step in for safety, coach for skills.',
  'The "five more minutes" trap ends with a timer and a warm, firm follow-through.',
  'Name the recurring battle, then fix it upstream — before it starts, not during.',
  'Every daily meltdown is a routine waiting to be built.',

  // ── Month 11 · Repair & Resilience ─────────────────────────────────────────
  "Rupture is normal; repair is the skill. It's the coming-back that builds the bond.",
  'When you lose it, own it: "I was too loud, and that wasn\'t about you." Repair beats perfection.',
  'Your apology teaches your child how to make one. Model the thing you want them to learn.',
  "There's no parent who never ruptures — only ones who repair and ones who don't.",
  "Repair isn't weakness. It's you showing that love survives hard moments.",
  'Mistakes are how kids learn, so let a few land. Rescue less, coach more.',
  'Say sorry without "but." A clean repair doesn\'t come with a defense.',
  'The story your child tells about a hard moment gets rewritten by your repair.',
  'Model self-forgiveness. Kids who see you recover learn they can too.',
  "Failure isn't the opposite of learning; it's part of it. Normalize the flop.",
  'When you circle back after a blowup, you teach that bonds are safe to break and mend.',
  'Praise the recovery, not just the success: "You were so mad, and you pulled it back together."',
  "Let your child struggle at the edge of their ability. That's where resilience is built.",
  '"You made a mistake" is a fact, not a verdict. Keep the child and drop the shame.',
  "Repair on your timeline, not their readiness. Reach out even if they're still prickly.",
  'Resilience grows from supported struggle, not from a path with every obstacle removed.',
  'Teach that being wrong is survivable by being wrong gracefully in front of them.',
  "The goal isn't a childhood without falls. It's a child who trusts they can get back up.",
  "After conflict, name what you'll do differently. Repair points forward, not just back.",
  "Your child doesn't need you to be right. They need you to come back.",
  "Hard feelings between you aren't the damage — unrepaired ones are. Do the repair.",
  'Let them fix their own small messes. Competence is built by doing hard things.',
  'When you model "I got that wrong, let me try again," you hand them a lifelong tool.',
  "Reconnection after rupture wires the brain for trust. It's some of your most important work.",
  "Don't erase the struggle to protect the feelings. Struggle, supported, grows them.",
  'A sincere ten-second repair outweighs an hour of guilt you keep to yourself.',
  'Teach your child that you can be angry and still be a team.',
  'Setbacks are data, not disasters. Ask "what did we learn?" and move on together.',
  'The bravest thing a parent models is admitting they were wrong and staying warm.',
  'Repair is the lesson your child leans on in every relationship for the rest of their life.',
  'However the day went, you can always end it with a return to each other.',

  // ── Month 12 · Sustain It ──────────────────────────────────────────────────
  'Consistency beats intensity. The parent who shows up steadily wins the long game.',
  "You can't sustain what depletes you. Guard your own rest like it's your child's.",
  'Parent from your values, not your mood. Decide who you want to be before the hard moment.',
  "Progress isn't a straight line. Zoom out on the bad days and you'll see the climb.",
  'The small stuff done daily is the big stuff. Boring consistency is the whole secret.',
  'Celebrate how far your child has come, not just how far there is to go.',
  'You are allowed to change your approach. Flexibility is strength, not failure.',
  'Compare your child to who they were last month, never to another child.',
  'Fill your own cup without guilt. A regulated you is the intervention that lasts.',
  "Pick one thing to work on at a time. You can't build every skill this week.",
  'The goal was never perfect parenting. It was a connected, capable kid and a bond that holds.',
  'On the hard days, lower the bar to "everyone\'s safe and loved." That\'s enough.',
  'Notice your own growth. The calm you found today was a skill you built.',
  'Rhythms outlast willpower. Build the habit and let it carry you on the tired days.',
  "Trust the process on the days you can't see the progress. Roots grow in the dark.",
  'Your child is a work in progress, and so are you. Give both of you room.',
  "Keep the long view: you're not managing today's behavior, you're raising a whole person.",
  "Rest is productive. It's what lets you come back tomorrow as the parent you want to be.",
  "Let good enough be good enough. Perfection isn't sustainable, and kids don't need it.",
  'The relationship is the goal that outlasts every phase. Protect it above the rules.',
  'Small wins compound. Keep stacking good moments and the hard ones lose their grip.',
  'You will get it wrong, come back, and get it right. That loop is the work.',
  'One calm, connected moment a day, repeated, becomes the childhood they remember.',
  "Keep going. The steady, ordinary love you give today is what they'll carry forever.",
];

// ─────────────────────────────────────────────────────────────────────────────
// CHALLENGES — (title, description). One small action for the day.
// ─────────────────────────────────────────────────────────────────────────────

const kChallengeSeeds = <(String, String)>[
  // ── Month 1 · Foundations ──────────────────────────────────────────────────
  (
    'The function question',
    'Pick one recurring behavior and ask: what is it helping my child get, or get away from?',
  ),
  (
    "Watch, don't fix",
    'Observe one tricky moment today without stepping in. Just notice what happens right before and after.',
  ),
  (
    'One warm hello',
    "Greet your child today like you're genuinely glad to see them — eye contact, full attention, ten seconds.",
  ),
  (
    'Describe it',
    'Narrate one behavior out loud with no label and no lecture. Just say what you see.',
  ),
  (
    'Small praise, big aim',
    'Catch and name one moment of the behavior you want more of today.',
  ),
  (
    'Lower one demand',
    'Find one task your child is fighting and make it smaller or easier today.',
  ),
  (
    'The ten-second pause',
    'Before reacting to the next frustrating moment, count ten slow seconds first.',
  ),
  (
    'Connect first',
    'Before your next correction, offer one moment of connection — a touch, a smile, their name.',
  ),
  (
    'Name the need',
    'Guess out loud what your child needs in one hard moment: "You need help," or "You need a break."',
  ),
  (
    'Thermostat check',
    'Notice your own tone once today, lower it on purpose, and watch what shifts.',
  ),
  (
    'One curious question',
    'Trade one command for a question you actually want the answer to.',
  ),
  (
    'Underneath it',
    'In one hard moment, look for the hidden cause: tired, hungry, overwhelmed, or scared.',
  ),
  (
    'Hold both',
    'Set one limit today while staying warm: "I won\'t let you hit, and I\'m right here."',
  ),
  (
    'Repair a small one',
    'Reconnect after one minor bump today, even a tiny one. Practice the loop.',
  ),
  (
    'Follow through once',
    "Say what you'll do, then calmly do it — one time, no repeating, no raising your voice.",
  ),
  (
    'Notice the good exit',
    'Point out one moment your child recovered or calmed down. Recovery deserves attention too.',
  ),
  (
    'One-on-one, phone away',
    'Give your child five minutes of undivided, device-free attention where they lead.',
  ),
  (
    'Skill, not will',
    'Reframe one "won\'t" as a "can\'t yet" today, and offer help instead of pressure.',
  ),
  ('Predictable warning', 'Give a clear heads-up before one transition today.'),
  ('Say less', 'In one tense moment, use half the words you normally would.'),
  (
    'Catch yourself labeling',
    'Notice one label you\'re tempted to use ("lazy," "dramatic") and swap it for a description.',
  ),
  (
    'Steady, not big',
    "Keep your reaction small during one behavior you'd usually meet loudly.",
  ),
  (
    'Meet reality',
    'Adjust one expectation today to match where your child actually is right now.',
  ),
  (
    'Borrow my calm',
    'In one storm, get low, slow your breathing, and just be a calm body nearby.',
  ),
  (
    'Name a win',
    'Tell your child one specific thing they did well today, out loud.',
  ),
  (
    'The real problem',
    'Pick one behavior and jot what might be driving it before deciding how to respond.',
  ),
  (
    'Relationship deposit',
    'Do one small thing today purely to strengthen the bond — no agenda attached.',
  ),
  (
    'One clear limit',
    'State one boundary calmly and simply, then stop explaining it.',
  ),
  (
    'Choose your battle',
    "Let one small thing go today that isn't worth the energy.",
  ),
  (
    'Warm tone test',
    'Give one instruction in a genuinely warm voice and notice the difference in response.',
  ),
  (
    'Start where they are',
    'Meet your child at their current mood before asking them to shift it.',
  ),

  // ── Month 2 · Reset the Parent ─────────────────────────────────────────────
  (
    'Name your weather',
    'Say your own feeling out loud once today: "I\'m feeling frustrated right now."',
  ),
  (
    'The long exhale',
    'In one tense moment, make your out-breath longer than your in-breath before you speak.',
  ),
  (
    'Spot the trigger',
    'Notice the exact moment your patience thins today, and name what set it off.',
  ),
  (
    'Thirty-second exit',
    'Step away for thirty seconds before responding to one heated moment.',
  ),
  (
    'Kinder story',
    'Catch one harsh thought about your child today and rewrite it more generously.',
  ),
  (
    'Fill your cup',
    "Do one small thing for yourself today, guilt-free, before you're empty.",
  ),
  (
    'Whisper it',
    "In one moment you'd usually raise your voice, lower it to a near-whisper instead.",
  ),
  (
    'HALT check',
    'Once today, pause and ask: am I hungry, angry, lonely, or tired?',
  ),
  (
    "Notice, don't judge",
    'Catch yourself mid-reaction once and just observe the urge without acting on it.',
  ),
  (
    'Repair your tone',
    'If your tone gets sharp today, circle back and own it without undoing the limit.',
  ),
  (
    'Drop the shoulders',
    'Three times today, check your body for tension and consciously soften it.',
  ),
  (
    'One boundary for you',
    'Protect one small pocket of time or energy for yourself today.',
  ),
  (
    'Forgive yesterday',
    "Let go of one parenting moment you're still beating yourself up over.",
  ),
  (
    'Model the breath',
    'Take one visible calming breath in front of your child today.',
  ),
  (
    'Lower the bar',
    "On today's hard moment, aim for safe and loved, not perfect.",
  ),
  (
    'Catch the story',
    'Notice one "they\'re doing this to me" thought and question whether it\'s true.',
  ),
  (
    'Pre-plan the trigger',
    'Name one predictable flashpoint today and decide your calm response in advance.',
  ),
  (
    'Ask your own need',
    'Once today, ask yourself "what do I need right now?" and honor the answer.',
  ),
  (
    'Stay the adult',
    'In one power struggle today, focus only on staying calm — not on winning.',
  ),
  (
    'Two-minute reset',
    'Take a two-minute break when you feel the fuse shortening.',
  ),
  (
    'Name it to model it',
    'Narrate one of your feelings and how you handled it, out loud.',
  ),
  (
    'Soften the self-talk',
    "Replace one \"I'm a bad parent\" thought with \"I'm a learning parent\" today.",
  ),
  (
    'Credit the recovery',
    'Catch yourself recovering from a hard moment and give yourself credit.',
  ),
  ('Guard your sleep', 'Do one thing tonight to protect your own rest.'),
  (
    "Respond, don't react",
    'Add a deliberate three-second pause before one reaction today.',
  ),
  (
    'Unclench',
    'Notice your jaw or fists in a tense moment and release them on purpose.',
  ),
  (
    'One kind thing',
    "Say one kind thing to yourself the way you'd say it to a friend.",
  ),
  (
    'Watch your fuel',
    'Eat or hydrate before the witching hour instead of running on empty.',
  ),
  (
    'Model repair',
    'After any slip today, show your child what a calm comeback looks like.',
  ),
  (
    'Name your limit',
    "Notice when you're near your edge and step back before you go over it.",
  ),
  (
    'Reset ritual',
    'Pick one small reset — a breath, a stretch, water — and use it once today.',
  ),

  // ── Month 3 · Connection ───────────────────────────────────────────────────
  (
    'Ten-minute lead',
    "Give your child ten minutes of play today where they're fully in charge.",
  ),
  (
    'Real hello',
    'Greet your child at your next reunion with full attention and a genuine smile.',
  ),
  (
    'Phone down',
    'Put your phone out of sight during one conversation with your child today.',
  ),
  (
    'Delight out loud',
    'Tell your child one specific thing you love about them today.',
  ),
  (
    'Get on their level',
    "Kneel or sit to your child's eye level for one interaction today.",
  ),
  (
    'Learn their world',
    'Ask your child to teach you something they love, and actually listen.',
  ),
  (
    'Fill the tank first',
    'Before your next big ask, give one warm moment of connection.',
  ),
  (
    'Overheard praise',
    'Let your child overhear you saying something kind about them today.',
  ),
  (
    'Snuggle reset',
    'Offer a five-minute cuddle before a predictably hard part of the day.',
  ),
  (
    'Play their game',
    'Join whatever your child is playing today, on their terms, for a few minutes.',
  ),
  ('Warm name', "Say your child's name warmly before your next request."),
  (
    'One good question',
    'Ask one question today just to know your child better, not to check on them.',
  ),
  (
    'Notice them',
    'Point out one specific thing you noticed your child do or feel today.',
  ),
  (
    'Reconnect first',
    'After the next hard moment, reach for connection before correction.',
  ),
  (
    'Undivided minutes',
    'Spend a few device-free minutes today doing nothing but being together.',
  ),
  (
    'Laugh together',
    'Do one silly thing today just to make your child laugh with you.',
  ),
  (
    'Special time',
    'Set up a small, predictable one-on-one moment your child can count on.',
  ),
  (
    'A kind touch',
    'Offer a hug, a hand, or a shoulder squeeze at a calm moment today.',
  ),
  (
    'Curious, not corrective',
    'Trade one correction today for a curious question about what happened.',
  ),
  (
    'Bedtime warmth',
    'End today with connection, not a recap of what went wrong.',
  ),
  (
    'Tank check',
    'Ask whether the connection tank is low before the next behavior spike.',
  ),
  (
    'Enjoy them',
    'Let your child see that you genuinely enjoy their company today.',
  ),
  (
    'Small repair',
    'Reconnect after one small disconnect today, even a tiny one.',
  ),
  (
    "Follow, don't lead",
    'Let your child pick the activity today and follow along happily.',
  ),
  ('Say yes more', 'Find one low-stakes "yes" to give your child today.'),
  (
    'Be interruptible',
    'When your child comes to you today, pause and turn toward them.',
  ),
  (
    'Their favorite',
    'Do one small thing today around something your child loves.',
  ),
  (
    'Warm goodbye',
    'Make one separation today feel warm and predictable, not rushed.',
  ),
  (
    'Notice the good',
    'Catch your child being kind or trying hard, and name it warmly.',
  ),
  (
    'Sit close',
    'In one quiet moment, just sit near your child with no agenda.',
  ),
  (
    'Connection deposit',
    'Make one deposit in the relationship today with no strings attached.',
  ),

  // ── Month 4 · Define the Goal ──────────────────────────────────────────────
  (
    'The instead',
    'Pick one behavior you want to stop and name what you want your child to do instead.',
  ),
  (
    'Positive opposite',
    'Turn one "don\'t" into a clear "do" you can teach today.',
  ),
  (
    'One skill focus',
    'Choose one skill to grow this week and let a smaller battle go.',
  ),
  (
    'Name the skill',
    'When your child does the thing you want, name the skill out loud.',
  ),
  (
    'Shrink the step',
    'Break one hard expectation into a first step your child can actually reach.',
  ),
  (
    'Catch the brick',
    "Notice and praise one small piece of the skill you're building today.",
  ),
  (
    'Teach when calm',
    'Practice a tricky skill with your child during a calm, low-stakes moment.',
  ),
  (
    "What's hard here",
    'Pick one recurring struggle and ask what skill your child is missing.',
  ),
  (
    'Reward the try',
    "Praise one attempt at a new skill today, even if it didn't work.",
  ),
  (
    'Model it first',
    'Show your child the behavior you want before you ask for it.',
  ),
  (
    'Picture the goal',
    'Get specific: what exactly do you want this behavior to look like?',
  ),
  (
    "Replace, don't remove",
    'Give your child a better way to get what the behavior was getting.',
  ),
  (
    'One rung up',
    "Set today's expectation just slightly above where your child is now.",
  ),
  (
    'Practice run',
    'Rehearse one tricky situation with your child before it happens.',
  ),
  (
    'The long view',
    "Ask which skill you're teaching today still matters when they're grown.",
  ),
  (
    "Coach, don't scold",
    'Turn one correction today into a quick coaching moment.',
  ),
  (
    'Frustration reps',
    'Let your child sit with one small frustration and coach them through it.',
  ),
  ('Name the win', 'Tell your child the name of the skill they just used.'),
  ('Small enough', "Make today's goal small enough that success is likely."),
  (
    'Same fight, new frame',
    'Reframe one recurring battle as a skill-building project.',
  ),
  (
    'Teach the ask',
    'Teach your child words to ask for something they usually grab or whine for.',
  ),
  (
    'Wait practice',
    'Give your child one small, supported chance to practice waiting today.',
  ),
  (
    'Flexibility rep',
    'Introduce one tiny change today and coach your child through the flex.',
  ),
  (
    'Ask for help',
    'Teach your child how to ask for help instead of melting down.',
  ),
  (
    'One clear aim',
    "Write down the one behavior you're working toward this week.",
  ),
  (
    'Notice progress',
    'Point out one way your child is a little better at something than before.',
  ),
  (
    'Repeat calmly',
    'Practice one skill with ten calm reps instead of one loud correction.',
  ),
  (
    'Effort over outcome',
    'Praise the effort your child put in today, regardless of the result.',
  ),
  (
    'Build the replacement',
    'Reinforce the good version of a behavior more than you react to the bad.',
  ),
  (
    'Teachable moment',
    'Find one calm moment today to teach a skill your child needs.',
  ),
  (
    'Aim you can name',
    "Define today's goal clearly enough that you'll both know it's working.",
  ),

  // ── Month 5 · Decode the Function ──────────────────────────────────────────
  (
    'Before and after',
    'Pick one behavior today and note what happened right before and right after.',
  ),
  (
    'Attention or escape',
    'Ask what one behavior is getting: attention, escape, a thing, or calm.',
  ),
  (
    'Track it',
    'Jot down one behavior each time it happens today and look for the pattern.',
  ),
  (
    'Check the antecedent',
    'For one behavior, change what happens right before it and watch what shifts.',
  ),
  (
    'Attention test',
    'Notice whether one behavior tends to happen when your attention is elsewhere.',
  ),
  (
    'Escape spotter',
    'Watch whether one behavior shows up mainly around hard or disliked tasks.',
  ),
  (
    'Tangible check',
    "Notice if a behavior happens when your child wants something they can't have.",
  ),
  (
    'Body first',
    "For one meltdown, ask whether it's a want or an overwhelmed body.",
  ),
  (
    'What did it get',
    'After one behavior today, ask honestly what it produced.',
  ),
  (
    'Not personal',
    'Reframe one frustrating behavior as information, not defiance.',
  ),
  (
    'Better way in',
    'Pick one behavior and offer a better way to get the same thing.',
  ),
  (
    'Spot the reward',
    'Notice what you do right after a behavior — you may be reinforcing it.',
  ),
  (
    'Upstream look',
    'For one "out of nowhere" behavior, look for what came before it.',
  ),
  (
    'Two questions',
    'Ask of one behavior: what set it off, and what did it achieve?',
  ),
  (
    'Function, then fix',
    'Name the function of one behavior before deciding how to respond.',
  ),
  (
    'Give connection free',
    'If a behavior is attention-driven, offer connection before it starts.',
  ),
  (
    'Shrink the demand',
    'If a behavior is escape-driven, make the task smaller and watch it ease.',
  ),
  (
    'Hold the limit',
    'If a behavior is tangible-driven, hold the limit and offer an alternative.',
  ),
  (
    'Calm the body',
    'If a behavior is regulation-driven, reduce the noise and stimulation first.',
  ),
  (
    'Same look, different why',
    'Notice one behavior that shows up in two settings for two reasons.',
  ),
  (
    'What it produces',
    'Finish the sentence: "This behavior reliably gets my child ___."',
  ),
  (
    'Change one thing',
    'Adjust one antecedent today and see if the behavior even happens.',
  ),
  ('Read the need', 'Guess the need under one behavior and meet it directly.'),
  (
    "Don't feed it",
    'Notice one behavior you may be accidentally rewarding, and stop.',
  ),
  (
    'Make the good work',
    'Make the appropriate behavior get the payoff the misbehavior was getting.',
  ),
  (
    'Detective mode',
    'Approach one behavior today like a curious detective, not a judge.',
  ),
  (
    'Pattern over incident',
    'Look at one behavior across the week, not just today.',
  ),
  (
    'Ask the behavior',
    'Imagine the behavior could talk — what would it say it needs?',
  ),
  (
    'Function log',
    'Write down the suspected function of one recurring behavior.',
  ),
  (
    'Test your guess',
    'Pick a suspected function and try the matching response once today.',
  ),
  (
    'See the why',
    "Practice looking past what one behavior looks like to why it's happening.",
  ),

  // ── Month 6 · Structure & Routines ─────────────────────────────────────────
  (
    'Make it visible',
    "Show your child what's coming today with a list, picture, or clear plan.",
  ),
  (
    'Night-before fix',
    'Prevent one morning battle by prepping the night before.',
  ),
  (
    'Five-minute warning',
    'Give a clear five-minute warning before one transition today.',
  ),
  ('First-then', 'Use one "first this, then that" instead of a command today.'),
  (
    'Set the stage',
    'Change one part of the environment to make good behavior easier.',
  ),
  (
    'Out of sight',
    'Remove one tempting thing before it starts a battle today.',
  ),
  (
    'Same steps',
    'Run one routine (bedtime, morning) in the exact same order today.',
  ),
  (
    'Let the timer decide',
    "Use a timer to end one activity so you don't have to be the bad guy.",
  ),
  (
    'Decide in advance',
    'Pick one rule and decide your response before the moment arrives.',
  ),
  (
    'Two choices',
    'At one hard moment, offer exactly two options instead of an open field.',
  ),
  (
    'Preview it',
    'Tell your child what to expect before one new or tricky situation.',
  ),
  (
    'Anchor point',
    'Protect one fixed point in the day your child can count on.',
  ),
  (
    'Check the basics',
    'Before correcting today, check sleep, food, and downtime first.',
  ),
  ('Boring is good', 'Keep one routine calm and boring on purpose today.'),
  (
    'Chart the boss',
    'Let a checklist or chart carry one instruction instead of your voice.',
  ),
  (
    "Prevent, don't react",
    'Fix one recurring problem upstream, before it happens.',
  ),
  (
    'Warn and acknowledge',
    'Before one transition, warn, then acknowledge the hard feeling.',
  ),
  (
    'Easy good choice',
    'Make the choice you want the easiest one to make today.',
  ),
  ('Rhythm over rule', 'Turn one nagging point into a predictable routine.'),
  (
    'Calm before the switch',
    'Slow down and steady yourself right before a hard transition.',
  ),
  (
    'One system fix',
    'Find one daily flashpoint and build a small routine around it.',
  ),
  (
    'Keep the promise',
    'Follow through on one routine exactly as you said you would.',
  ),
  (
    'Consistent no',
    'Hold one small limit consistently today so it stops getting tested.',
  ),
  (
    'Reduce the chaos',
    'Lower the noise or clutter in one moment before addressing behavior.',
  ),
  (
    'Transition object',
    'Give your child something to move toward, not just something ending.',
  ),
  (
    'Predictable consequence',
    "State a consequence calmly before it's needed, not after.",
  ),
  ('Same time, same place', 'Do one daily task at a consistent time today.'),
  (
    'Visual countdown',
    'Use a visual or timer to make one wait concrete for your child.',
  ),
  (
    'Build one rail',
    'Add one small structure to a part of the day that keeps falling apart.',
  ),
  (
    'Design the path',
    'Set up one situation today so the good choice is the obvious one.',
  ),
  (
    'Steady beats loud',
    'Handle one repeat issue with a calm routine instead of a bigger reaction.',
  ),

  // ── Month 7 · Limits & Follow-through ──────────────────────────────────────
  (
    'Say it once',
    'Give one instruction a single time today, then calmly follow through.',
  ),
  (
    'Empathy plus limit',
    'Pair one boundary with empathy: "I know, and the answer is still no."',
  ),
  ('Hold the line', 'Keep one limit today even through the protest.'),
  ('Quiet after the no', 'Give one limit, then stop explaining it.'),
  (
    'Choice inside the line',
    'Offer a choice within a boundary, not about it, today.',
  ),
  (
    "Only what you'll keep",
    "Make only limits today that you're actually willing to enforce.",
  ),
  (
    'Calm certainty',
    'Deliver one boundary with quiet confidence instead of volume.',
  ),
  ('Follow through once', "Say what you'll do, then do it calmly, one time."),
  (
    'Small and related',
    "Choose a consequence today that's small, related, and certain.",
  ),
  (
    'Full sentence',
    'Use "I won\'t let you ___" as a complete, calm limit today.',
  ),
  (
    "Don't take the bait",
    'Refuse to argue one boundary today — state it and stay steady.',
  ),
  (
    'Weather the tantrum',
    'Hold one limit through the meltdown without caving.',
  ),
  ("Say what you'll do", 'Phrase one limit as your action, not their command.'),
  (
    'No empty threats',
    "Skip one threat today you know you won't follow through on.",
  ),
  (
    'Firm and warm',
    'Hold one boundary while staying physically warm and close.',
  ),
  (
    'Decide the bottom line',
    'Pick one non-negotiable and decide it before the moment.',
  ),
  (
    'Let the world teach',
    'Allow one safe natural consequence to do the teaching today.',
  ),
  (
    'Warn once',
    'Give one warning, then follow through — no second and third chances.',
  ),
  ('Steady body', 'Keep your body calm and grounded during one limit today.'),
  ('Boundary as fact', 'Deliver one limit like a fact, not a fight.'),
  (
    'Hold without lecturing',
    'Enforce one limit today with as few words as possible.',
  ),
  (
    'Keep your word',
    'Follow through on one thing you told your child would happen.',
  ),
  (
    "Don't cave to tears",
    'Hold one reasonable limit even when the crying starts.',
  ),
  (
    'Safe and firm',
    "Be both your child's safe place and their boundary in one moment.",
  ),
  (
    'Pre-decide the response',
    'Plan your calm response to one predictable limit-test today.',
  ),
  (
    'Consequence, not crossfire',
    'Let a consequence teach while keeping the relationship warm.',
  ),
  (
    'One clear boundary',
    'State one boundary simply and clearly, then hold it.',
  ),
  (
    'Mean it quietly',
    'Enforce one limit today without raising your voice at all.',
  ),
  (
    'Both, not either',
    'Give one limit with both firmness and tenderness together.',
  ),
  (
    'Reliable words',
    'Make your words reliable today by matching them with action.',
  ),
  (
    'Line stays put',
    'Keep one line exactly where it was, no matter the reaction.',
  ),

  // ── Month 8 · Big Feelings ─────────────────────────────────────────────────
  (
    'Name it to tame it',
    "Put words to your child's feeling once today before doing anything else.",
  ),
  (
    'Feeling, then behavior',
    'Welcome one big feeling while gently redirecting the behavior.',
  ),
  ('Comfort first', 'In one meltdown, comfort before you correct or explain.'),
  (
    'Be the anchor',
    'Stay calm and close through one storm instead of trying to stop it.',
  ),
  (
    'Safe and here',
    'Say "You\'re safe, I\'m here" during one hard moment today.',
  ),
  (
    'Validate before solve',
    'Acknowledge one feeling before offering any solution.',
  ),
  (
    'Look underneath',
    'For one angry moment, name the hurt or fear beneath it.',
  ),
  ('Lower your voice', "When your child's voice rises today, drop yours."),
  (
    'Let it pass',
    'Let one feeling run its course without rushing it out the door.',
  ),
  (
    'Sit beside the storm',
    'Just stay near your child through one big feeling today.',
  ),
  (
    "Witness, don't fix",
    'Offer "I see you" instead of a fix during one hard feeling.',
  ),
  (
    'Feelings have an end',
    'Remind your child once today that all feelings pass.',
  ),
  (
    'Reconnect after',
    'After one storm, reconnect before you talk about what happened.',
  ),
  (
    'Somewhere to go',
    'Give one big feeling a physical outlet today: a squeeze, stomp, or breath.',
  ),
  (
    "Don't take it personally",
    'Let one "I hate you" roll off as feeling, not truth.',
  ),
  (
    'Model a feeling',
    'Name one of your own feelings and how you handled it, calmly.',
  ),
  (
    'Borrow my calm',
    "Be the steady body your child's nervous system can borrow from.",
  ),
  (
    'Notice, name, allow',
    'Walk through notice-name-allow with one feeling today.',
  ),
  (
    'Big adult, not bigger',
    'Meet one big feeling with steadiness, not escalation.',
  ),
  (
    'Honor the want',
    'Acknowledge one disappointment: "You really wanted that."',
  ),
  ('Just listen', 'Listen to one feeling today without any advice.'),
  (
    'Calm ground',
    'Wait for calm before teaching the lesson after one meltdown.',
  ),
  (
    'Stay through it',
    "Make sure your child isn't alone in one hard feeling today.",
  ),
  (
    'Two things true',
    'Hold "I love you" and "the answer is no" together in one moment.',
  ),
  (
    'Slow exhale together',
    'Take a slow breath alongside your child in one upset moment.',
  ),
  ('Name the size', 'Help your child name how big a feeling is today.'),
  (
    'Brave and scared',
    'Tell your child today that brave and scared can live together.',
  ),
  (
    'Empathy first',
    "Lead with empathy in one moment you'd usually lead with a rule.",
  ),
  (
    'Weather the wave',
    'Treat one meltdown as a wave to ride, not an emergency to stop.',
  ),
  (
    'Presence over words',
    'Offer presence, not explanation, during one flooded moment.',
  ),
  (
    'Coach the calm',
    'Guide your child toward one calming tool after the feeling eases.',
  ),

  // ── Month 9 · Respond with Purpose ─────────────────────────────────────────
  (
    'Catch them being good',
    'Notice and name three good behaviors before dinner today.',
  ),
  (
    'Specific praise',
    'Praise one specific action today instead of a general "good job."',
  ),
  (
    'Reinforce the replacement',
    'The moment your child uses the good behavior, warmly acknowledge it.',
  ),
  (
    'Fast yes',
    'Respond quickly today when your child asks the appropriate way.',
  ),
  (
    'Name the skill',
    'Praise one behavior by naming the skill: "That was patience."',
  ),
  (
    'Reward effort',
    'Praise the effort or strategy today, not just the result.',
  ),
  (
    'Spotlight the try',
    'Give your attention to one attempt in the right direction.',
  ),
  (
    'Quick and sincere',
    'Give one small, immediate, genuine bit of praise today.',
  ),
  (
    'Make the calm ask work',
    'Make sure the polite request gets a faster response than the loud one.',
  ),
  (
    'Mirror them',
    'Reflect one good quality back: "You kept trying even when it was hard."',
  ),
  (
    'Notice recovery',
    'Praise your child for calming down or recovering today.',
  ),
  (
    'Reinforce the peace',
    'Reconnect after cooperation today, not just after conflict.',
  ),
  (
    'Brief correction',
    'Keep one correction short and make one praise specific.',
  ),
  (
    'Best attention',
    'Give your best, not your leftover, attention to a good moment.',
  ),
  (
    'Thank the behavior',
    'Say "thank you for ___" about one exact behavior you want more of.',
  ),
  (
    "Reinforce, not bribe",
    'Notice good behavior after it happens, not to stop a fit before.',
  ),
  (
    'Progress, not perfection',
    'Praise one step of progress today, imperfect as it is.',
  ),
  (
    'Grow it with attention',
    'Pick one good behavior and pour attention on it today.',
  ),
  (
    'Show your delight',
    'Let your delight show when your child does the right thing.',
  ),
  (
    'Private praise',
    'Offer one quiet, specific bit of praise just between you two.',
  ),
  (
    'Immediate high-five',
    'Celebrate one hard-won behavior the moment it happens.',
  ),
  (
    'Feed the good',
    "Give more energy to the behavior you want than the one you don't.",
  ),
  (
    'Name their success',
    'Help your child name what they did well so they can repeat it.',
  ),
  (
    'Ten-second notice',
    'Take ten seconds today to notice a small good moment out loud.',
  ),
  (
    'Starve the drama',
    'Give one attention-seeking behavior a calm, small response today.',
  ),
  (
    'Reinforce the ask',
    'Reward your child for using words instead of a behavior today.',
  ),
  (
    'Yes, like that',
    'Give a quick "yes, like that" when your child gets it right.',
  ),
  (
    'Notice the calm',
    'Point out one calm, cooperative moment today and appreciate it.',
  ),
  (
    'Effort tally',
    "Count and name your child's efforts today, not just their wins.",
  ),
  (
    'Reward the recovery',
    'Acknowledge how your child pulled themselves back together today.',
  ),
  (
    'Aim the spotlight',
    'Choose on purpose which behavior gets your attention today.',
  ),

  // ── Month 10 · Everyday Battles ────────────────────────────────────────────
  (
    'Prep the morning',
    'Lay out clothes, bags, and the plan tonight for tomorrow.',
  ),
  ('Feed first', 'Offer a snack before a predictably cranky time today.'),
  (
    'Store plan',
    'Say the expectations out loud before walking into a store today.',
  ),
  (
    'Timer ends screens',
    'Let a timer, not you, signal the end of screen time today.',
  ),
  ('Shared goal', 'In one sibling squabble, name what they both want.'),
  (
    "Coach, don't referee",
    'Step back from one small sibling conflict and let them try to solve it.',
  ),
  (
    'Front-load bedtime',
    'Add a few minutes of connection to the start of bedtime tonight.',
  ),
  (
    'Shrink the homework',
    'Ask for just the first problem or first line today.',
  ),
  (
    'Two non-negotiables',
    'Pick your two must-holds today and flex on the rest.',
  ),
  ('Car warm-up', 'Set expectations in the car before one outing today.'),
  (
    'Teach the words',
    'Give your child the exact words to use instead of whining today.',
  ),
  (
    'Out-the-door list',
    'Make a checklist your child can own for leaving the house.',
  ),
  (
    'Calm-time attention',
    'Give siblings attention at calm times so they stop competing for it.',
  ),
  (
    'Drop the food pressure',
    'Offer the meal and let go of making your child eat it today.',
  ),
  (
    'Warning plus next',
    'End one fun activity with a warning and a thing to move toward.',
  ),
  (
    'Boring car-seat routine',
    'Use the same calm car-seat routine every time today.',
  ),
  (
    'Decide bedtime early',
    'Set the bedtime limit before the tired negotiation starts.',
  ),
  ('First-then chores', 'Frame one chore as "first this, then that."'),
  (
    'Practice at home',
    'Rehearse one public behavior at home before you need it out.',
  ),
  (
    'Countdown for the dawdler',
    'Give a countdown and a small job instead of nagging today.',
  ),
  ("Name what's next", "At one screen transition, name what's coming next."),
  (
    'Coach the toy trade',
    'Help two kids negotiate one shared toy instead of taking it.',
  ),
  ('Fix the rush', 'Change one thing about the morning system, not the child.'),
  ('Snack and plan', 'Pack a snack and a simple plan before one outing today.'),
  (
    'Unhurried bedtime',
    'Give bedtime ten extra minutes tonight so it can stay calm.',
  ),
  (
    'Protect the bond',
    'In one homework fight, shrink the demand and keep the relationship.',
  ),
  (
    'Let them solve it',
    'Let siblings handle one small conflict; step in only for safety.',
  ),
  (
    'Warm five-more-minutes',
    'Use a timer and a warm follow-through on one "five more minutes."',
  ),
  (
    'Upstream fix',
    'Pick one daily battle and change what happens right before it.',
  ),
  (
    'Build the routine',
    'Turn one recurring meltdown into a small, repeatable routine.',
  ),
  (
    'One calm handoff',
    'Make one transition today calm and predictable from start to finish.',
  ),

  // ── Month 11 · Repair & Resilience ─────────────────────────────────────────
  (
    'Own it',
    'If you lose your cool today, name it and own your part without a "but."',
  ),
  ('Clean apology', 'Offer one apology today with no defense attached.'),
  ('Circle back', 'Return to one hard moment later today and reconnect.'),
  (
    'Model the comeback',
    'Show your child what a calm recovery looks like after a slip.',
  ),
  (
    'Let a mistake land',
    'Resist rescuing your child from one small, safe mistake today.',
  ),
  (
    'Praise the recovery',
    'Notice out loud how your child pulled themselves back together.',
  ),
  (
    'Supported struggle',
    'Let your child work at the edge of hard while you stay near.',
  ),
  (
    'Fact, not verdict',
    'Frame one mistake as "you made a mistake," not "you are bad."',
  ),
  (
    'Repair on your timeline',
    "Reach out to reconnect even if your child is still prickly.",
  ),
  (
    'Self-forgiveness out loud',
    'Model forgiving yourself for one mistake in front of your child.',
  ),
  (
    'Fix their own mess',
    'Let your child clean up one small mess they made today.',
  ),
  ('Try again', 'Say "I got that wrong, let me try again" once today.'),
  (
    'What did we learn',
    'After one setback, ask together what you both learned.',
  ),
  (
    'Repair points forward',
    "After one conflict, name what you'll do differently next time.",
  ),
  (
    'Come back warm',
    'End one hard moment by returning to warmth, whatever happened.',
  ),
  (
    'Normalize the flop',
    'Tell your child about a time you failed and what you learned.',
  ),
  (
    'Angry and a team',
    'Remind your child you can be upset and still on their side.',
  ),
  (
    'Ten-second repair',
    'Do one quick, sincere repair instead of stewing in guilt.',
  ),
  (
    'Let them get up',
    'Encourage your child to try again after one fall or fail today.',
  ),
  (
    'Drop the shame',
    "Correct one behavior today while keeping your child's worth intact.",
  ),
  ('Reconnect after rupture', 'Rebuild the bond after one hard moment today.'),
  (
    'Growth over perfect',
    "Praise one thing your child is working on, not just what they nailed.",
  ),
  ('Admit one wrong', 'Admit one small thing you got wrong today, calmly.'),
  (
    'Struggle, witnessed',
    'Stay present while your child struggles instead of jumping in.',
  ),
  ('Setback as data', 'Treat one setback today as information, not disaster.'),
  ('End with return', 'However today went, end it by returning to each other.'),
  (
    'Repair teaches repair',
    'Let your child see a full rupture-and-repair loop today.',
  ),
  ('Brave admission', 'Say "I was wrong" to your child today and stay warm.'),
  (
    'Trust the get-up',
    'Show confidence that your child can recover from one hard thing.',
  ),
  ('Hand it back', 'Hand one small problem back to your child to solve today.'),
  (
    'Mend it',
    'Notice one small rupture today and mend it before the day ends.',
  ),

  // ── Month 12 · Sustain It ──────────────────────────────────────────────────
  (
    'One thing at a time',
    'Pick one skill or habit to focus on this week and let the rest go.',
  ),
  (
    'Guard your rest',
    'Protect your own sleep or downtime tonight without guilt.',
  ),
  (
    'Parent your values',
    'Name one value you want to lead with today, before the hard moment.',
  ),
  ('Zoom out', 'On a hard day, look back a month and notice the progress.'),
  (
    'Celebrate the climb',
    "Tell your child one specific way they've grown lately.",
  ),
  ('Fill your cup', 'Do one restoring thing for yourself today, guilt-free.'),
  (
    'Compare to last month',
    'Measure your child against their past self, not another child.',
  ),
  (
    'Lower the bar',
    'On a hard day, aim only for "safe and loved" and call it enough.',
  ),
  (
    'Notice your growth',
    'Name one way you handled today better than you would have before.',
  ),
  ('Trust the roots', "Trust the process on a day you can't see the progress."),
  ('Good enough', 'Let one thing be good enough today instead of perfect.'),
  ('Count a small win', 'Notice and count one small win today.'),
  (
    'Choose the bond',
    'Choose the relationship over being right in one moment today.',
  ),
  (
    'Flex the plan',
    "Change one approach that isn't working, without calling it failure.",
  ),
  (
    'Steady over intense',
    'Show up steadily today rather than trying to fix everything.',
  ),
  (
    'Values check',
    'Ask if one reaction today matched the parent you want to be.',
  ),
  (
    'Room to grow',
    'Give both you and your child grace for being works in progress.',
  ),
  ('Rest is fuel', 'Treat one bit of rest today as fuel, not laziness.'),
  (
    'Long view',
    "Remember today that you're raising a whole person, not managing a moment.",
  ),
  ('Stack the good', 'Add one more good moment to the pile today.'),
  (
    'Come back again',
    'Get one thing wrong today and come back to make it right.',
  ),
  ('One calm moment', 'Create one calm, connected moment today on purpose.'),
  (
    'Kind to yourself',
    "Talk to yourself today the way you'd talk to a struggling friend.",
  ),
  ('Keep going', "Notice you're still showing up, and let that count today."),
];

// ─────────────────────────────────────────────────────────────────────────────
// REFLECTIONS — one prompt each (ReflectionPrompt.prompt)
// ─────────────────────────────────────────────────────────────────────────────

const kReflectionPrompts = <String>[
  // ── Month 1 · Foundations ──────────────────────────────────────────────────
  'What is one behavior I want to understand better this month?',
  "When I look under my child's hardest behavior, what might they be needing?",
  'Where did I react today when I wanted to respond?',
  'What did my calm — or lack of it — do to the room today?',
  'When did my child seem most understood by me today?',
  'What skill might my child still be learning, behind the behavior that frustrated me?',
  "What did I attend to more today — the behavior I want, or the one I don't?",
  'Where did I connect before I corrected? Where did I forget to?',
  'What is one moment I handled better than I would have a year ago?',
  'What am I making it mean about me when my child struggles?',
  'When did I lower a demand today, and how did it go?',
  'What triggered me most today, and what was underneath my reaction?',
  'Where did I hold a limit and a feeling at the same time?',
  "What is one label I'm tempted to put on my child — and is it actually true?",
  'When did I model the calm I want my child to learn?',
  "What did I let go of today that wasn't worth the fight?",
  'Where did I say too much when less would have helped?',
  'What does my child do that I secretly admire?',
  'When did I follow through calmly, and what did it teach?',
  'What part of today do I want to repair or revisit with my child?',
  "How did I fill my child's connection tank today?",
  'What expectation am I holding that might not match where my child is?',
  'When did I feel most like the parent I want to be today?',
  "What behavior am I feeding with attention that I'd rather starve?",
  'Where did I assume "won\'t" when it might have been "can\'t yet"?',
  "What did my child's body tell me today that their words didn't?",
  'When did I choose the relationship over being right?',
  'What went sideways today, and what was I feeling right before it did?',
  'What is one thing I want to do differently tomorrow morning?',
  'Where did I show my child that repair is always possible?',
  "After this first month, what's shifting in how I see my child's behavior?",

  // ── Month 2 · Reset the Parent ─────────────────────────────────────────────
  'What triggered me most today, and what was underneath my reaction?',
  'Where did I stay the adult when I wanted to react?',
  'What did my body feel right before I lost my patience today?',
  'How full was my own cup today, and what would refill it?',
  "What story did I tell myself about my child's behavior — and was it fair?",
  'Where did I need to step away today, and did I?',
  'What did I model about handling hard feelings today?',
  'What am I still holding against myself that I could set down?',
  'When did I catch my reaction before it ran away with me?',
  'What do I need more of this week to parent from calm?',
  'Where did guilt drive my parenting today instead of my values?',
  'How did I talk to myself after a hard moment — kindly or harshly?',
  'What is one trigger I can prepare for before tomorrow?',
  'When did I lend my calm today, and when did I lend my chaos?',
  'What did resting — or not resting — do to my patience today?',
  'Where did I whisper when I wanted to yell, or wish I had?',
  'What need of mine went unmet today, and how did it show up?',
  'When did I forgive myself today, and did it help?',
  'What would the calm version of me have done differently today?',
  'Where did I notice my fuse getting short before it blew?',
  'How did I refuel today, if at all?',
  'What am I proud of in how I handled myself today?',
  'When did I pause before reacting, and what came of it?',
  'What self-talk do I want to change for tomorrow?',
  "Where was I hard on myself when I'd have been gentle with a friend?",
  'What helped me come back to calm today?',
  'When did my own regulation change the room?',
  'What is one kind thing I can do for myself tonight?',
  'Where did my mood, not my values, run the show today?',
  'What did I learn about my own limits today?',
  'How do I want to show up for myself tomorrow?',

  // ── Month 3 · Connection ───────────────────────────────────────────────────
  'When did I feel most connected to my child today?',
  "How did I fill my child's connection tank today?",
  'Where did I put connection before correction?',
  'When did my child seem to feel truly seen by me?',
  'What did I notice and enjoy about my child today?',
  'Where did I turn toward my child instead of away?',
  'When did I give my full, undivided attention today?',
  "What did I learn about my child's world today?",
  'How did I show my child I delight in them?',
  'Where did the phone or a task pull me away from them?',
  'When did we laugh or play together today?',
  'What small moment of closeness happened today?',
  'Where did I reconnect after a hard moment?',
  'How did I greet my child at our reunions today?',
  'What is one thing my child shared that I really listened to?',
  "When did I follow my child's lead today?",
  'What did being present — or absent — do to the day?',
  'Where could I have connected but rushed past instead?',
  'When did my warmth make the next ask easier?',
  'How is the connection tank looking lately, honestly?',
  'What did I do today purely for the relationship?',
  'When did I say something kind about or to my child?',
  'Where did I choose closeness over efficiency today?',
  'What does my child seem to need more of from me right now?',
  'When did a small touch or word land for my child today?',
  'How did I make a goodbye or transition feel warm today?',
  'What did I notice my child do that I want to remember?',
  'Where did I let my child know they matter today?',
  'When did I stop and truly see my child today?',
  'What deposit did I make in our relationship today?',
  'How do I want to connect with my child tomorrow?',

  // ── Month 4 · Define the Goal ──────────────────────────────────────────────
  'What skill was hiding under the behavior that frustrated me today?',
  'What am I trying to build in my child right now, beyond stopping a behavior?',
  'Where did I coach a skill instead of just correcting today?',
  'What "don\'t" could I turn into a teachable "do"?',
  'When did I reward an attempt, not just a success, today?',
  'What is the one skill I most want to grow this month?',
  'Where did I aim at compliance when I could have aimed at capability?',
  'What did I model today that I want my child to learn?',
  "When did I catch a small piece of the skill I'm building?",
  "What's genuinely hard for my child in our biggest recurring battle?",
  'Where did I set the bar too high or too low today?',
  'What replacement behavior am I teaching for the one I want gone?',
  'When did I name a skill out loud for my child today?',
  "What long-term quality am I nurturing through today's small moments?",
  'Where did I turn a battle into a lesson today?',
  'What did I practice with my child during a calm moment?',
  'When did I praise effort over outcome today?',
  'What "won\'t" might actually be a "can\'t yet" for my child?',
  'How small could I make the next step so my child can succeed?',
  'What is one skill my child got a little better at recently?',
  'Where did I teach instead of punish today?',
  "What do I want this behavior to look like when it's going well?",
  'When did I give the good skill more attention than the bad habit?',
  "What lesson plan is my child's hardest behavior handing me?",
  "Where am I expecting a skill I haven't actually taught?",
  'When did I reframe a frustration as a skill to build?',
  "What progress can I name in the skill we're working on?",
  'How am I helping my child practice waiting, sharing, or flexing?',
  'What did I do today that will still matter when my child is grown?',
  'Where could I trade a command for a teaching moment tomorrow?',
  'What one goal do I want to hold clearly this week?',

  // ── Month 5 · Decode the Function ──────────────────────────────────────────
  'What was one behavior today really trying to get or avoid?',
  'What happened right before the behavior that surprised me most?',
  'Where did I take a behavior personally that was really just a need?',
  'What did I do right after a behavior that might have reinforced it?',
  'When did I see the same behavior spring from a different cause?',
  'What function have I been missing on our most stubborn behavior?',
  'Where did changing the antecedent change the behavior today?',
  'What need was underneath the behavior I found hardest today?',
  'When did attention turn out to be the fuel for a behavior?',
  'Where was a behavior really about escaping something too hard?',
  'What did I notice about when the behavior tends to show up?',
  'What did the behavior reliably produce for my child today?',
  'Where did I offer a better way to meet the same need?',
  'When did I act like a detective instead of a judge today?',
  "What pattern is emerging in the behavior I've been tracking?",
  "What was my child's body telling me, past the behavior itself?",
  'Where did I calm the body before addressing the behavior?',
  'When did I accidentally make the misbehavior work today?',
  'What could I change upstream to prevent the behavior tomorrow?',
  'Where did naming the function make me feel calmer about it?',
  'What two things set off and paid off the behavior today?',
  'When did I confuse a want with an overwhelmed nervous system?',
  "What behavior am I feeding that I'd rather starve?",
  'Where did I make the appropriate behavior worth more today?',
  'What did the timing of the behavior tell me about its cause?',
  'When did I stop guessing and actually look at the function?',
  'What have I learned about why this behavior keeps happening?',
  'Where did I meet the need instead of just stopping the behavior?',
  'What function would I guess for our hardest current struggle?',
  'When did seeing the "why" change how I responded?',
  "What experiment could I run to test a behavior's function?",

  // ── Month 6 · Structure & Routines ─────────────────────────────────────────
  'Which part of today felt most chaotic, and what structure might help?',
  'Where did a lack of warning turn into a battle today?',
  'What routine carried us smoothly through a hard moment?',
  'Where did I decide a rule in the heat of the moment instead of ahead?',
  'What in the environment set my child up to struggle today?',
  'When did a timer or chart do a job I usually do with my voice?',
  'What morning or bedtime friction could a night-before fix prevent?',
  'Where did I hold a limit consistently, and did the testing ease?',
  'What transition went better because I gave a heads-up?',
  'When did predictability seem to calm my child today?',
  "What basic — sleep, food, downtime — was missing behind today's behavior?",
  'Where could two clear choices have replaced an open-ended ask?',
  'What routine did I keep or break today, and what did it cost or save?',
  'When did I win a transition in the calm moments before it?',
  'What one flashpoint keeps recurring that I could build a routine around?',
  'Where did I make the good choice the easy choice today?',
  'What did previewing — or not previewing — do for a tricky moment?',
  'When did structure feel like warmth rather than control today?',
  'What tempting thing could I move out of sight to prevent a battle?',
  'Where did chaos invite big behavior today?',
  "What promise-shaped routine is building my child's trust in my word?",
  'When did I let the schedule hold the limit for me?',
  'What small rail could I add to a part of the day that keeps collapsing?',
  'Where did a five-minute warning save a meltdown?',
  'What consistency am I glad I held today?',
  'When did reducing the noise or clutter change the behavior?',
  'What did I fix upstream today, before it became a problem?',
  'Where did I design a situation so the good choice was obvious?',
  'What routine do I want to protect more fiercely?',
  'When did boring-and-predictable do its quiet work today?',
  'What one system could I tighten before tomorrow?',

  // ── Month 7 · Limits & Follow-through ──────────────────────────────────────
  'Where did I hold a limit with warmth today?',
  'When did I say something once and follow through, and how did it go?',
  'Where did I over-explain a boundary instead of just holding it?',
  'What limit did I hold through the protest today?',
  'When did I offer a choice inside a boundary rather than about it?',
  "Where did I make a threat I wasn't willing to keep?",
  'What did my calm certainty do for a limit today?',
  'When did I cave, and what did the caving teach?',
  'Where did I pair a boundary with empathy today?',
  'What limit felt hard to hold, and what made it hard?',
  'When did I let a natural consequence do the teaching?',
  'Where did I keep my body calm while holding a line?',
  "What did following through reliably do for my child's trust today?",
  'When did I argue a boundary I could have simply held?',
  'Where did firmness and tenderness work together today?',
  'What non-negotiable did I decide before the moment, and did it help?',
  'When did I raise my voice when quiet certainty would have worked?',
  'Where did I keep my word to my child today?',
  'What limit am I glad I held, looking back on the day?',
  'When did a tantrum test a boundary, and how did I do?',
  'Where could I have said less and still held the line?',
  'What did I learn about my own follow-through today?',
  'When did I let the consequence teach and keep the relationship warm?',
  'Where did I wobble on a limit, and what would steady me next time?',
  'What boundary is worth holding more consistently this week?',
  'When did "I won\'t let you" do the job without a lecture?',
  'Where did I confuse firm with harsh, or kind with permissive?',
  'What limit felt like a gift to my child, even if they protested?',
  'When did my child feel safe because I held the line?',
  'Where did I stay steady when my child fell apart?',
  'What follow-through do I want to strengthen tomorrow?',

  // ── Month 8 · Big Feelings ─────────────────────────────────────────────────
  "When did I stay calm through my child's storm today?",
  'Where did I comfort before I corrected?',
  'What feeling did I help my child name today?',
  'When did I try to stop a feeling instead of letting it pass?',
  "What was underneath my child's anger or upset today?",
  'Where did my presence help my child come back down?',
  'When did I validate a feeling before offering a solution?',
  "What did lowering my voice do when my child's rose?",
  'Where did I take a big feeling personally today?',
  'When did I sit beside the storm instead of fighting it?',
  'What did my child need most in their hardest moment today?',
  'Where did I reconnect after a meltdown before teaching?',
  'When did I model handling my own feeling well today?',
  "What helped my child's body settle today?",
  'Where did I rush a feeling that needed more time?',
  'When did "I\'m here with you" do more than any explanation?',
  "What did I learn about my child's emotions today?",
  'Where did I meet a big feeling with an even bigger reaction?',
  'When did I let my child know their feeling was allowed?',
  'What outlet helped a big feeling move through today?',
  'Where did I stay the calm one when it was hard?',
  'When did I witness a feeling instead of trying to fix it?',
  'What did co-regulation look like for us today?',
  'Where did I offer empathy first today?',
  'When did I hold love and a limit at the same time?',
  'What feeling is my child working hardest to manage right now?',
  'Where did I help my child feel less alone in a hard moment?',
  'When did I keep my cool while my child lost theirs?',
  'What did I do that helped a storm pass faster today?',
  'Where could I have led with more empathy today?',
  "How do I want to show up for my child's big feelings tomorrow?",

  // ── Month 9 · Respond with Purpose ─────────────────────────────────────────
  'What good behavior did I catch and name today?',
  'Where did I give my best attention to the behavior I want more of?',
  'When did I praise a specific action instead of a general "good job"?',
  'What effort did I notice and reward today, apart from the outcome?',
  'Where did the calm ask get a faster response than the loud one?',
  'When did I reinforce a replacement behavior the moment it appeared?',
  'What did my attention grow today — the good or the not-good?',
  'Where did I reconnect after cooperation, not just conflict?',
  'When did I let my delight show as my child got it right?',
  'What skill did I name for my child as I praised it?',
  'Where did I keep a correction brief and a praise specific?',
  'When did I respond to progress rather than perfection?',
  'What small step in the right direction did I notice today?',
  "Where did I accidentally reward the behavior I don't want?",
  'When did I make the good behavior clearly worth it?',
  'What behavior am I trying to grow with attention right now?',
  'Where did I starve a bit of drama with a calm response today?',
  'When did I praise the recovery, not just the success?',
  'What did quick, sincere praise do in the moment today?',
  'Where could I have noticed something good that I missed?',
  'When did I reward my child for using words instead of a behavior?',
  'What did I appreciate out loud today?',
  'Where did my leftover attention go when my best could have?',
  'When did I help my child name their own success?',
  'What good moment did I take ten seconds to notice today?',
  'Where did I choose on purpose what to give attention to?',
  'When did reinforcement, not bribery, teach today?',
  'What behavior got stronger because I noticed it today?',
  'Where did I feed the good more than I reacted to the bad?',
  "When did my attention change my child's behavior today?",
  'What good thing do I want to be sure to notice tomorrow?',

  // ── Month 10 · Everyday Battles ────────────────────────────────────────────
  'Which daily battle drained me most today, and what drives it?',
  'Where did prepping ahead prevent a meltdown today?',
  'What did hunger or tiredness fake as "bad behavior" today?',
  'When did a timer end a screen better than I could have?',
  'Where did I name the shared goal in a sibling fight today?',
  'What morning friction could a night-before fix prevent?',
  'When did front-loading connection ease a hard routine today?',
  'Where did shrinking a demand cool a homework or chore battle?',
  'What two things did I hold, and what did I let go today?',
  'When did setting expectations early make an outing smoother?',
  'Where did I coach instead of referee today?',
  'What recurring battle could I fix upstream instead of during?',
  'When did I drop the pressure at mealtime, and what happened?',
  'Where did a warning and a next thing smooth a transition today?',
  'What did the morning rush reveal about our system?',
  'When did I give the dawdler a job instead of a nag?',
  'Where did I protect the relationship inside a daily struggle?',
  'What public moment went better because we practiced at home?',
  'When did siblings solve something themselves today?',
  'Where did I turn a chore into a first-then?',
  'What daily meltdown is really a routine waiting to be built?',
  'When did a calm, boring routine defuse a usual fight?',
  'Where did I negotiate with a tired child when I could have decided earlier?',
  'What snack or plan saved an outing today?',
  "When did naming what's next soften a transition?",
  'Where did bedtime go better with more time and less hurry?',
  'What battle am I ready to redesign instead of re-fight?',
  'When did I keep my cool during a predictable flashpoint today?',
  "Where could a small system change save tomorrow's rush?",
  'What did I learn about the pattern behind one daily struggle?',
  'Which everyday battle do I most want to fix this week?',

  // ── Month 11 · Repair & Resilience ─────────────────────────────────────────
  'Where did I rupture today, and did I repair it?',
  'When did I own my part without a "but"?',
  'What did my apology model for my child today?',
  'Where did I let a small mistake land instead of rescuing?',
  "When did I praise my child's recovery today?",
  'What struggle did I let my child work through with support?',
  "Where did I keep my child's worth intact while correcting?",
  'When did I circle back to reconnect after a hard moment?',
  'What did modeling "let me try again" teach today?',
  'Where did I treat a setback as data instead of disaster?',
  'When did I show my child that being wrong is survivable?',
  'What repair am I still owing that I could make tomorrow?',
  'Where did I let my child fix their own small mess today?',
  'When did I reach out even though my child was still prickly?',
  'What did coming back after a blowup teach about our bond?',
  'Where did I choose repair over being right today?',
  'When did I forgive myself for a mistake in front of my child?',
  'What resilience did my child show today that I can name?',
  'Where did I rush to rescue when I could have coached?',
  'When did I stay warm while admitting I was wrong?',
  'What did we learn together from a setback today?',
  'Where did I show my child that anger and being a team can coexist?',
  'When did a quick repair beat hours of quiet guilt?',
  'What mistake of mine became a lesson today?',
  'Where did supported struggle grow my child today?',
  'When did I point our repair forward, not just back?',
  'What did my child learn about getting back up today?',
  'Where did I mend a rupture before the day ended?',
  'When did admitting a wrong bring us closer?',
  'What repair skill do I most want my child to carry?',
  'However today went, how did I return to my child?',

  // ── Month 12 · Sustain It ──────────────────────────────────────────────────
  'What one thing am I choosing to focus on this week?',
  'How did I guard my own rest today?',
  'Which of my values did I parent from today?',
  'Where did I zoom out and see progress on a hard day?',
  'What growth in my child did I celebrate today?',
  'How did I refill my own cup this week?',
  "Where did I compare my child to their past self, not another child?",
  'When did "safe and loved" turn out to be enough today?',
  'What did I handle better today than I would have a year ago?',
  "Where did I trust the process when I couldn't see results?",
  'What did I let be good enough today?',
  'What small win am I counting tonight?',
  'Where did I choose the relationship over being right?',
  "What approach did I flex because it wasn't working?",
  'Where did steady beat intense today?',
  'What reaction today matched — or missed — the parent I want to be?',
  'What grace did I give myself and my child today?',
  'How did rest fuel my parenting this week?',
  "What reminds me I'm raising a whole person, not managing a moment?",
  'What good moment did I add to the pile today?',
  'Where did I get it wrong, come back, and get it right?',
  'What one calm, connected moment did I create today?',
  'How am I different, as a parent, than I was a year ago?',
  'What do I want to carry forward from this year into the next?',
];
